### ISSUE TITLE
Personal TODO list

### ISSUE THREAD

**Issue by Rotekoppen** [Rotekoppen/arpeggio-bot#3]
- [ ] Show how the track was queued, (playlist, lastFM, manually, ETC)
- [ ] Better queue managment
- [ ] Better emoji managment
- [ ] Better bot murdering (if it crashes or gets killed)
- [ ] Better skipping
- [ ] Announce skipping (?)
- [ ] DJ role
- [ ] Better randomization without chance of not getting a track
- [ ] Update dependencies
- [ ] Better quality playback
